### ISSUE TITLE
(MINILSM) 震惊！project-scott MiniLSM被曝出现0day漏洞，你还敢用吗？

### ISSUE THREAD

**Issue by chuigda** [ICEYSELF/project-scott#24]
由于合并算法的问题，MiniLSM中的高level的blocks可能出现interleave！但是根据LSM的规则，高层次level中是不能出现interleave的！
![图片](https://user-images.githubusercontent.com/29348140/75062903-ac850500-551e-11ea-9422-b74e4a6236a3.png)
这在之前的`get`算法下一直没有暴露，但是在换用对block间关系十分敏感的二分搜索法之后这种问题出现了！database之后就会上传，让大家看看这到底是怎么一回事。
对于project-scott曝出0 day漏洞这件事，小编只想说如果开发者没有用心的话，用再先进的技术，再优秀的工具链都是没有用的！希望制作组尽快意识到这一点！亡羊补牢为时不晚！

**Comment by chuigda** [comment]
[rop_test_db.zip](https://github.com/ICEYSELF/project-scott/files/4237626/rop_test_db.zip)
发生故障的数据可以在这里下载到

**Comment by chuigda** [comment]
我们可以做一个思想实验，假设我们的block size是4，我们在LV-3有这样3个block：
```
[AAA AAB AAW AAX](1) [ABA ABB ABC ABD](2) [ABE ABF ABG ABH](3)
```
现在从LV-2来了两个block：
```
[AAW AAX AAY AAZ](4) [ABE ABF ABX ABY](5)
```
很显然，4会和1合并，5会和2合并；但是这两个合并并不是独立进行，而是一同进行的。在合并之后，获得的结果应该是：
```
[ABA ABB ABC ABD](2)
[AAA AAB AAW AAX](6) [AAY AAZ ABE ABF](7) [ABG ABH ABX ABY](8)
```
很显然7和2出现了interleave。
稍后我推一个test上来复现这个情况。

**Comment by chuigda** [comment]
> 对于project-scott曝出0 day漏洞这件事，小编只想说如果开发者没有用心的话，用再先进的技术，再优秀的工具链都是没有用的！希望制作组尽快意识到这一点！亡羊补牢为时不晚！

十三亿人民天天被震惊。

**Comment by chuigda** [comment]
另外为了方便调试，我觉得应该加一个Write Only WAL进来。

**Comment by chuigda** [comment]
要从根本上解决这个问题，我们只需要让原先被检定为overlapping blocks之间的block也参与merge就可以了。事实上，这简化了我们的问题，我们可以把输入的所有blocks看作一个巨大的range `[LOW, HIGH]`，然后判定跟这个range `INTERLEAVE`的所有block就可以了。为了最佳性能，最好使用二分法。下面是一段伪代码。
```pascal
FUNCTION OVERLAPPING-LOWER-BOUND(R: [LOW, HIGH], BLOCKS: [[LOW, HIGH]; N]): USIZE
BEGIN
	LEFT  = 0
	RIGHT = N
	WHILE LEFT < RIGHT DO
		MID = (LEFT + RIGHT) / 2
		[MID-LOW, MID-HIGH] = BLOCKS[MID]
		IF MID-LOW > LOW THEN
			RIGHT = MID
		ELSE IF MID-HIGH < LOW THEN
			LEFT = MID + 1
		ELSE
			OVERLAPPING-LOWER-BOUND = MID
		END IF
	END WHILE
	OVERLAPPING-LOWER-BOUND = LEFT
END

FUNCTION OVERLAPPING-UPPER-BOUND(R: [LOW, HIGH], BLOCKS: [[LOW, HIGH]; N]): USIZE
BEGIN
	LEFT  = 0
	RIGHT = N
	WHILE LEFT < RIGHT DO
		MID = (LEFT + RIGHT) / 2
		[MID-LOW, MID-HIGH] = BLOCKS[MID]
		IF MID-LOW > HIGH THEN
			RIGHT = MID
		ELSE IF MID-HIGH < HIGH THEN
			LEFT = MID + 1
		ELSE
			OVERLAPPING-UPPER-BOUND = MID
		END IF
	END WHILE
	OVERLAPPING-UPPER-BOUND = RIGHT
END
```

**Comment by chuigda** [comment]
![图片](https://user-images.githubusercontent.com/29348140/75088022-69f51400-5582-11ea-8b25-7a0bd5add184.png)
还是有问题

刚刚又跑了一次测试，这是这次测试获得的database和failure report
[rop_test_failure.zip](https://github.com/ICEYSELF/project-scott/files/4238967/rop_test_failure.zip)

**Comment by chuigda** [comment]
![图片](https://user-images.githubusercontent.com/29348140/75091039-15629080-55a4-11ea-851d-732b75cc8baf.png)
尽管从逻辑上来说我们的算法没什么问题，但是还是出错了。看来得针对性地test一下。

**Comment by ICEYSELF** [comment]
```
DBG_LOG: merging [wl_test_db_lv2_32.msst@[aec, aee], wl_test_db_lv2_31.msst@[adu, aeb], wl_test_db_lv2_30.msst@[adm, adt], wl_test_db_lv2_29.msst@[ade, adl]] at level 2 into [wl_test_db_lv3_0.msst@[ach, aco], wl_test_db_lv3_1.msst@[acp, acw], wl_test_db_lv3_2.msst@[acx, ajd], wl_test_db_lv3_3.msst@[art, art]]
DBG_LOG: will participate in merging: []
DBG_LOG: will stand still: [wl_test_db_lv3_0.msst@[ach, aco], wl_test_db_lv3_1.msst@[acp, acw], wl_test_db_lv3_2.msst@[acx, ajd], wl_test_db_lv3_3.msst@[art, art]]
DBG_LOG: newly produced blocks are [wl_test_db_lv3_4.msst@[ade, adl], wl_test_db_lv3_5.msst@[adm, adt], wl_test_db_lv3_6.msst@[adu, aeb], wl_test_db_lv3_7.msst@[aec, aee]]
```

**Comment by ICEYSELF** [comment]
尽管在最近的提交里纠正了input blocks的次序问题，但是问题仍然存在。

**Comment by chuigda** [comment]
![图片](https://user-images.githubusercontent.com/29348140/75091688-2fec3800-55ab-11ea-82c6-6a007b479d8a.png)

这里，lower_idx和upper_idx同时都为2。按理说这里的upper_idx应该是inclusive的。关键的点在于，我们应该让upper_idx保持exclusive的语义，所以上面那个overlapping-upper-bound应该修复一下。我猜把最后那个else分支删掉就好了。

**Comment by chuigda** [comment]
```pascal
FUNCTION OVERLAPPING-UPPER-BOUND(R: [LOW, HIGH], BLOCKS: [[LOW, HIGH]; N]): USIZE
BEGIN
	LEFT  = 0
	RIGHT = N
	WHILE LEFT < RIGHT DO
		MID = (LEFT + RIGHT) / 2
		[MID-LOW, MID-HIGH] = BLOCKS[MID]
		IF MID-LOW > HIGH THEN
			RIGHT = MID
		ELSE
			LEFT = MID + 1
		END IF
	END WHILE
	OVERLAPPING-UPPER-BOUND = RIGHT
END
```
接下来要做的就是一些清理工作了。我们早就应该用`log`模块代替`eprintf`来打印调试信息的。
